services:
  postgres:
    image: postgres:16-alpine
    hostname: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - ./db/postgres:/var/lib/postgresql/data
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - qlch-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.2
    command: "start-dev --import-realm"
    restart: on-failure
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "9095:8080"
    volumes:
#      - ./identity/theme:/opt/keycloak/themes
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - postgres
    networks:
      - qlch-network

networks:
  qlch-network:
    driver: bridge
    name: qlch-network