server:
  port: 9090

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: meeting-service
          uri: lb://meeting-service
          predicates:
            - Path=/meeting/**
          filters:
            - RewritePath=/(?<segment>.*), /api/${segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/(?<segment>.*), /api/${segment}
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/document/**
          filters:
            - RewritePath=/(?<segment>.*), /api/${segment}
        - id: meeting-history-ws
          uri: lb:ws://meeting-history-service
          predicates:
            - Path=/meeting-history/ws/**
          filters:
            - RewritePath=/(?<segment>.*), /api/${segment}
        - id: meeting-history-service
          uri: lb://meeting-history-service
          predicates:
            - Path=/meeting-history/**
          filters:
            - RewritePath=/(?<segment>.*), /api/${segment}
        - id: vote-service
          uri: lb://vote-service
          predicates:
            - Path=/vote/**
          filters:
            - RewritePath=/(?<segment>.*), /api/${segment}
        - id: speech-service
          uri: lb://speech-service
          predicates:
            - Path=/speech/**
          filters:
            - RewritePath=/(?<segment>.*), /api/${segment}
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
