spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/meeting_history
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      acks: 1
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.vdt.commonlib.dto, org.vdt.qlch.meetinghistoryservice.model"
      auto-offset-reset: latest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/VDT

eureka:
  instance:
    hostname: meeting-history-service
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

gateway-url: http://api-gateway:9090