spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://identity.vdt.io.vn/realms/VDT
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  auth-server-url: https://identity.vdt.io.vn
  realm: VDT
  resource: user-management # client-id
  credentials:
    secret: p8o2LT7RdfZznZxtLJpYBDC3OyfngFrC