server:
  port: 8082
  servlet:
    context-path: /api/user
spring:
  application:
    name: user-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

cors:
  allowed-origins: '*'