spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/document
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/VDT

eureka:
  instance:
    hostname: document-service
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

