server:
  port: 8083
  servlet:
    context-path: /api/document

spring:
  application:
    name: document-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

cloudinary:
  url: ${CLOUDINARY_URL}

cors:
  allowed-origins: '*'

