server:
  port: 8081
  servlet:
    context-path: /api/meeting

spring:
  application:
    name: meeting-service

cors:
  allowed-origins: '*'

vdt:
  services:
    user: ${gateway-url}/user
    document: ${gateway-url}/document