server:
  port: 8085
  servlet:
    context-path: /api/vote

spring:
  application:
    name: vote-service

vdt:
  services:
    meeting: ${gateway-url}/api/meeting
    document: ${gateway-url}/api/document
    user: ${gateway-url}/api/user
